package sistema.entidade;
// Generated 25/08/2017 19:03:45 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Tbos generated by hbm2java
 */
public class Tbos  implements java.io.Serializable {


     private Integer os;
     private Tbclientes tbclientes;
     private Date dataOs;
     private String tipo;
     private String situacao;
     private String equipamento;
     private String defeito;
     private String servico;
     private int idUsuario;
     private BigDecimal valor;
     private int status;

    public Tbos() {
    }

	
    public Tbos(Tbclientes tbclientes, Date dataOs, String tipo, String situacao, String equipamento, String defeito, int idUsuario, int status) {
        this.tbclientes = tbclientes;
        this.dataOs = dataOs;
        this.tipo = tipo;
        this.situacao = situacao;
        this.equipamento = equipamento;
        this.defeito = defeito;
        this.idUsuario = idUsuario;
        this.status = status;
    }
    public Tbos(Tbclientes tbclientes, Date dataOs, String tipo, String situacao, String equipamento, String defeito, String servico, int idUsuario, BigDecimal valor, int status) {
       this.tbclientes = tbclientes;
       this.dataOs = dataOs;
       this.tipo = tipo;
       this.situacao = situacao;
       this.equipamento = equipamento;
       this.defeito = defeito;
       this.servico = servico;
       this.idUsuario = idUsuario;
       this.valor = valor;
       this.status = status;
    }
   
    public Integer getOs() {
        return this.os;
    }
    
    public void setOs(Integer os) {
        this.os = os;
    }
    public Tbclientes getTbclientes() {
        return this.tbclientes;
    }
    
    public void setTbclientes(Tbclientes tbclientes) {
        this.tbclientes = tbclientes;
    }
    public Date getDataOs() {
        return this.dataOs;
    }
    
    public void setDataOs(Date dataOs) {
        this.dataOs = dataOs;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(String situacao) {
        this.situacao = situacao;
    }
    public String getEquipamento() {
        return this.equipamento;
    }
    
    public void setEquipamento(String equipamento) {
        this.equipamento = equipamento;
    }
    public String getDefeito() {
        return this.defeito;
    }
    
    public void setDefeito(String defeito) {
        this.defeito = defeito;
    }
    public String getServico() {
        return this.servico;
    }
    
    public void setServico(String servico) {
        this.servico = servico;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


