package sistema.entidade;
// Generated 25/08/2017 19:03:45 by Hibernate Tools 4.3.1



/**
 * Tbusuarios generated by hbm2java
 */
public class Tbusuarios  implements java.io.Serializable {


     private int idusuario;
     private String usuario;
     private String fone;
     private String login;
     private String senha;
     private String perfil;
     private int status;

    public Tbusuarios() {
    }

	
    public Tbusuarios(int idusuario, String usuario, String login, String senha, String perfil, int status) {
        this.idusuario = idusuario;
        this.usuario = usuario;
        this.login = login;
        this.senha = senha;
        this.perfil = perfil;
        this.status = status;
    }
    public Tbusuarios(int idusuario, String usuario, String fone, String login, String senha, String perfil, int status) {
       this.idusuario = idusuario;
       this.usuario = usuario;
       this.fone = fone;
       this.login = login;
       this.senha = senha;
       this.perfil = perfil;
       this.status = status;
    }
   
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getFone() {
        return this.fone;
    }
    
    public void setFone(String fone) {
        this.fone = fone;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public String getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(String perfil) {
        this.perfil = perfil;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


