/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.ui;
import java.awt.Color;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import sistema.entidade.Tbclientes;
import sistema.util.HibernateUtil;

/**
 *
 * @author gui1_
 */
public class BuscaCliente extends javax.swing.JFrame {
    public String[] aux = new String[8];
    private String ativo = "1";
    /**
     * Creates new form SistemaBusca
     */
    public BuscaCliente() {
        initComponents();
        
    }
    
    //variável que guarda a pesquisa ao banco
    private static String query_nome="from Tbclientes cli where cli.nomecli like '";
    //Método que executa a query
    private void executaQueryNome()
    {
        //completando a query com o campo de texto e setando para encontrar apenas com status=1
        executarHQLQuery(query_nome + txtCliente.getText() + "%' and status='"+ativo.toString()+"'");
        btnBusCliAltera.setEnabled(true);
    }
    //setando o cliente na tabela
        public void setar_campos()
    {
        int setar = tblBuscliResultado.getSelectedRow();       
        for (int i=0;i<aux.length;i++)
        {
        aux[i] = tblBuscliResultado.getModel().getValueAt(setar, i).toString();
        }
    }
        //enviando o cliente e abrindo a tela de cadastro
        public void envia_cliente()
        {
            CadastroCliente cliente = new CadastroCliente();
            CadastroCliente.txtCadCliId.setText(aux[0]);
            CadastroCliente.txtCadCliNome.setText(aux[1]);
            CadastroCliente.txtCadCliFone.setText(aux[2]);
            CadastroCliente.txtCadCliCpf.setText(aux[3]);
            CadastroCliente.txtCadCliEnd.setText(aux[4]);
            CadastroCliente.txtCadCliBairro.setText(aux[5]);
            CadastroCliente.txtCadCliCidade.setText(aux[6]);
            CadastroCliente.txtCadCliEmail.setText(aux[7]);
            cliente.setVisible(true);
            cliente.btnCadCliAdiciona.setEnabled(false);
            cliente.btnCadCliAltera.setEnabled(true);
            cliente.btnCadCliApagar.setEnabled(true);
            cliente.lblCadCliSit.setText("Alterando Cliente");
            cliente.lblCadCliSit.setForeground(Color.blue);
            this.dispose();
        }
    //Esse método chama o Hibernate para executar a consulta, esse método usa a classe de utilitário HibernateUtil.java
    private void executarHQLQuery(String hql)
    {
        try
        {
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        session.getTransaction();
        Query q = session.createQuery(hql);
        System.out.println(hql);
        //JOptionPane.showMessageDialog(null, q.getQueryString());
        List resultLista = q.list();
        mostraTabela(resultLista);
        session.getTransaction().commit();
        }
        catch (HibernateException he)
        {
            he.printStackTrace();
            
        }
    }
    //Método para colocar na tabela
    private void mostraTabela(List resultLista)
    {
        Vector<String> cabecaTabela = new Vector<String>();
        Vector dadoTabela = new Vector();
        cabecaTabela.add("Id");
        cabecaTabela.add("Nome");
        cabecaTabela.add("Telefone");
        cabecaTabela.add("CPF");
        cabecaTabela.add("Endereço");
        cabecaTabela.add("Bairro");
        cabecaTabela.add("Cidade");
        cabecaTabela.add("E-mail");
        
        for (Object o : resultLista)
        {
            Tbclientes cliente = (Tbclientes)o;
            Vector<Object> umaLinha = new Vector<Object>();
            umaLinha.add(cliente.getIdcli());
            umaLinha.add(cliente.getNomecli());
            umaLinha.add(cliente.getFonecli());
            umaLinha.add(cliente.getCpfcli());
            umaLinha.add(cliente.getEndcli());
            umaLinha.add(cliente.getBairrocli());
            umaLinha.add(cliente.getCidadecli());
            umaLinha.add(cliente.getEmailcli());
            dadoTabela.add(umaLinha);
        }
        tblBuscliResultado.setModel(new DefaultTableModel(dadoTabela, cabecaTabela));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnConsulta = new javax.swing.JButton();
        txtCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuscliResultado = new javax.swing.JTable();
        btnBusCliAltera = new javax.swing.JButton();
        radioBusCliAtivo = new javax.swing.JRadioButton();
        RadioBusCliInativo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("|Busca de clientes");

        jLabel1.setText("Nome cliente");

        btnConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/imagens/pesquisabttnmenor.png"))); // NOI18N
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });

        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });
        txtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClienteKeyTyped(evt);
            }
        });

        tblBuscliResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Telefone", "Endereço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBuscliResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBuscliResultadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBuscliResultado);

        btnBusCliAltera.setText("Alterar");
        btnBusCliAltera.setToolTipText("Clique para alterar cliente selecionado");
        btnBusCliAltera.setEnabled(false);
        btnBusCliAltera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusCliAlteraActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioBusCliAtivo);
        radioBusCliAtivo.setSelected(true);
        radioBusCliAtivo.setText("Clientes Ativos");
        radioBusCliAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBusCliAtivoActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioBusCliInativo);
        RadioBusCliInativo.setText("Clientes Inativos");
        RadioBusCliInativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBusCliInativoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(btnBusCliAltera)))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(radioBusCliAtivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RadioBusCliInativo)
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBusCliAtivo)
                    .addComponent(RadioBusCliInativo))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBusCliAltera)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(631, 294));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        
    }//GEN-LAST:event_txtClienteActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        executaQueryNome();
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void tblBuscliResultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBuscliResultadoMouseClicked
        setar_campos();
    }//GEN-LAST:event_tblBuscliResultadoMouseClicked

    private void btnBusCliAlteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusCliAlteraActionPerformed
        envia_cliente();
    }//GEN-LAST:event_btnBusCliAlteraActionPerformed

    private void radioBusCliAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBusCliAtivoActionPerformed
        ativo = "1";
    }//GEN-LAST:event_radioBusCliAtivoActionPerformed

    private void RadioBusCliInativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBusCliInativoActionPerformed
        ativo = "0";
    }//GEN-LAST:event_RadioBusCliInativoActionPerformed

    private void txtClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteKeyReleased
        
    }//GEN-LAST:event_txtClienteKeyReleased

    private void txtClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteKeyTyped
        executaQueryNome();
    }//GEN-LAST:event_txtClienteKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioBusCliInativo;
    private javax.swing.JButton btnBusCliAltera;
    private javax.swing.JButton btnConsulta;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioBusCliAtivo;
    private javax.swing.JTable tblBuscliResultado;
    private javax.swing.JTextField txtCliente;
    // End of variables declaration//GEN-END:variables
}
