/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.ui;

import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;
import sistema.entidade.Tbclientes;
import sistema.util.HibernateUtil;

/**
 *
 * @author gui1_
 */
public class CadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();
    }
    //query para inserir cliente
    private static String query_insere="INSERT INTO Tbclientes (nomecli,endcli,bairrocli,cepcli,cidadecli,emailcli,fonecli)";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCadCliNome = new javax.swing.JTextField();
        txtCadCliEnd = new javax.swing.JTextField();
        txtCadCliBairro = new javax.swing.JTextField();
        txtCadCliCep = new javax.swing.JTextField();
        txtCadCliCidade = new javax.swing.JTextField();
        txtCadCliEmail = new javax.swing.JTextField();
        txtCadCliFone = new javax.swing.JTextField();
        btnCadCliAdiciona = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtCadCliId = new javax.swing.JTextField();
        btnCadCliAltera = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtCadCliCpf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lblCadCliSit = new javax.swing.JLabel();
        btnCadCliApagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Cliente");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro Cliente");

        jLabel2.setText("*Nome");

        jLabel3.setText("Endereço");

        jLabel4.setText("Bairro");

        jLabel5.setText("CEP");

        jLabel6.setText("Cidade");

        jLabel7.setText("Email");

        jLabel8.setText("*Telefone");

        txtCadCliNome.setText(" ");

        btnCadCliAdiciona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/imagens/salvabttn.png"))); // NOI18N
        btnCadCliAdiciona.setToolTipText("Adicionar um novo cliente");
        btnCadCliAdiciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadCliAdicionaActionPerformed(evt);
            }
        });

        jLabel9.setText("Identificador");

        txtCadCliId.setEditable(false);

        btnCadCliAltera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/imagens/alterabttn.png"))); // NOI18N
        btnCadCliAltera.setToolTipText("Cliente para salvar as alterações");
        btnCadCliAltera.setEnabled(false);
        btnCadCliAltera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadCliAlteraActionPerformed(evt);
            }
        });

        jLabel10.setText("CPF");

        jLabel11.setText("*Obrigatório");

        lblCadCliSit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCadCliSit.setForeground(new java.awt.Color(102, 102, 102));
        lblCadCliSit.setText("Cadastrando");

        btnCadCliApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/imagens/cancelabttn.png"))); // NOI18N
        btnCadCliApagar.setToolTipText("Clique para apagar o cliente");
        btnCadCliApagar.setEnabled(false);
        btnCadCliApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadCliApagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCadCliId, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel11))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCadCliNome, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCadCliCpf))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCadCliCep, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCadCliCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCadCliEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCadCliFone, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(12, 12, 12)
                                    .addComponent(txtCadCliEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblCadCliSit)
                                    .addGap(135, 135, 135)
                                    .addComponent(jLabel1)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCadCliBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btnCadCliAdiciona)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadCliAltera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadCliApagar)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCadCliSit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCadCliId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCadCliNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtCadCliCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCadCliEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtCadCliBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadCliCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txtCadCliCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCadCliEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtCadCliFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadCliAdiciona)
                    .addComponent(btnCadCliAltera)
                    .addComponent(btnCadCliApagar))
                .addGap(51, 51, 51))
        );

        setSize(new java.awt.Dimension(569, 351));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadCliAdicionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadCliAdicionaActionPerformed
        insere_cliente();
    }//GEN-LAST:event_btnCadCliAdicionaActionPerformed

    private void btnCadCliAlteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadCliAlteraActionPerformed
        altera_cliente();
    }//GEN-LAST:event_btnCadCliAlteraActionPerformed

    private void btnCadCliApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadCliApagarActionPerformed
        inativa_cliente();
        
    }//GEN-LAST:event_btnCadCliApagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }
    //Método para inativar cliente
    private void inativa_cliente()
    {
        if (txtCadCliId.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Nenhum cliente selecionado!");
        }
        else
        {
            try {
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Query query = session.createSQLQuery("UPDATE `tbclientes` SET `status` = '0' where `idcli`'="+txtCadCliId.getText()+"'");
        //JOptionPane.showMessageDialog(null, query.getQueryString());
        query.executeUpdate();
        session.getTransaction().commit();
        session.close();
        txtCadCliNome.setText(null);
        txtCadCliId.setText(null);
        txtCadCliCpf.setText(null);
        txtCadCliCidade.setText(null);
        txtCadCliBairro.setText(null);
        txtCadCliCep.setText(null);
        txtCadCliEmail.setText(null);
        txtCadCliFone.setText(null);
        txtCadCliEnd.setText(null);
        JOptionPane.showMessageDialog(null, "Apagado com sucesso efetuado com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        }
    }
    //Método que o botão altera cliente chama
    private void altera_cliente()
    {
        if (txtCadCliNome.getText().isEmpty() || txtCadCliFone.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Existem campos obrigatórios em branco!");
        }
        else
        {
        executaAltera_Cliente("UPDATE `tbclientes` SET `nomecli` = '"+txtCadCliNome.getText()+"', `endcli` = '"+txtCadCliEnd.getText()+"', `bairrocli` = '"+txtCadCliBairro.getText()+"', `cidadecli` = '"+txtCadCliCidade.getText()+"', `cepcli` = '"+txtCadCliCep.getText()+"', `fonecli` = '"+txtCadCliFone.getText()+"', `emailcli` = '"+txtCadCliEmail.getText()+"', `cpfcli` = '"+txtCadCliCpf.getText()+"'  WHERE `tbclientes`.`idcli` = '"+txtCadCliId.getText()+"';");
        }
    }
    //Método que executa a alteração de cliente
    private void executaAltera_Cliente(String sql)
    {
        try {
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Query query = session.createSQLQuery(sql);
        query.executeUpdate();
        session.getTransaction().commit();
        session.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        txtCadCliNome.setText(null);
        txtCadCliId.setText(null);
        txtCadCliCpf.setText(null);
        txtCadCliCidade.setText(null);
        txtCadCliBairro.setText(null);
        txtCadCliCep.setText(null);
        txtCadCliEmail.setText(null);
        txtCadCliFone.setText(null);
        txtCadCliEnd.setText(null);
        JOptionPane.showMessageDialog(null, "Alteração efetuado com sucesso!");
    }
    private void insere_cliente()
    {
        if (txtCadCliNome.getText().isEmpty() || txtCadCliFone.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Existem campos obrigatórios em branco!");
        }
        else
        {
        executaHQLQuery("INSERT INTO Tbclientes (nomecli,endcli,bairrocli,cepcli,cidadecli,emailcli,fonecli,cpfcli,status)"+"values('"+txtCadCliNome.getText()+"','"+txtCadCliEnd.getText()+"','"+txtCadCliBairro.getText()+"','"+txtCadCliCep.getText()+"','"+txtCadCliCidade.getText()+"','"+txtCadCliEmail.getText()+"','"+txtCadCliFone.getText()+"','"+txtCadCliCpf.getText()+"','1')");
        }
    }
    
    private void executaHQLQuery(String hql)
    {
        try
        {
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Query query = session.createSQLQuery(hql);
        query.executeUpdate();
        session.getTransaction().commit();
        session.close();
        }
        catch (HibernateException e)
        {
            e.printStackTrace();
        }
        txtCadCliNome.setText(null);
        txtCadCliId.setText(null);
        txtCadCliCpf.setText(null);
        txtCadCliCidade.setText(null);
        txtCadCliBairro.setText(null);
        txtCadCliCep.setText(null);
        txtCadCliEmail.setText(null);
        txtCadCliFone.setText(null);
        txtCadCliEnd.setText(null);
        JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso!");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnCadCliAdiciona;
    public static javax.swing.JButton btnCadCliAltera;
    public static javax.swing.JButton btnCadCliApagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel lblCadCliSit;
    public static javax.swing.JTextField txtCadCliBairro;
    public static javax.swing.JTextField txtCadCliCep;
    public static javax.swing.JTextField txtCadCliCidade;
    public static javax.swing.JTextField txtCadCliCpf;
    public static javax.swing.JTextField txtCadCliEmail;
    public static javax.swing.JTextField txtCadCliEnd;
    public static javax.swing.JTextField txtCadCliFone;
    public static javax.swing.JTextField txtCadCliId;
    public static javax.swing.JTextField txtCadCliNome;
    // End of variables declaration//GEN-END:variables
}
